human_hub/human_hub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = []

urlpatterns += (
    i18n_patterns(
    path('', include('showcase.urls')),
    path('administration/', include('administration.urls')),
    path('orders/', include('orders.urls')),
    path('info/', include('info.urls')),
    path('admin/', admin.site.urls),
    )
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

human_hub/info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('discounts/', views.DiscountsView.as_view(), name='discounts'),
    path('refund/', views.RefundView.as_view(), name='refund'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('sizing/', views.SizingView.as_view(), name='sizing'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'about'}, name='about_tag'),
    path('contacts_tag/', views.AboutTagView.as_view(), {'tag': 'contacts'}, name='contacts_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'discounts'}, name='discounts_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'refund'}, name='refund_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'shipping'}, name='shipping_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'sizing'}, name='sizing_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'aboutermst'}, name='aboutermst_tag'),

]

human_hub/showcase/urls.py
from django.urls import path
from . import views

app_name = 'showcase'

urlpatterns = [
    path('', views.ShowcaseView.as_view(), name='showcase'),
    path('category/<int:category_id>/', views.CategoryPageView.as_view(), name='category_page'),
    path('item/<int:item_id>/', views.ItemPageView.as_view(), name='item_page'),
    path('category/<int:item_id>/sizes/', views.ChooseSizes, name='choose_sizes'),
    path("currency/<str:valuta>/", views.cart_val, name="currency"),
]

human_hub/templates/base.html
{% load i18n %}
{% load static %}
{% load showcase_tags %}
<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8" />
            <title>{% block title %}{% endblock %}</title>
            <meta name="Description" content="{% block description %}{% endblock %}">
            <meta name="viewport" content="width=device-width,initial-scale=1.0">
            <link rel="icon" href="{{ STATIC_URL }}img/Bornto_B_logo.png">
            <link href='https://fonts.googleapis.com/css?family=IBM Plex Mono' rel='stylesheet'>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"/>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


            {% block css %}{% endblock %}

            <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    </head>

    <style type="text/css">
        @font-face {
            font-family: "IBM Plex Mono";
            src: url(https://fonts.googleapis.com/css?family=IBM Plex Mono) format("truetype");
        }
        p.customfont {
            font-family: "IBM Plex Mono", Verdana, Tahoma;
        }
    </style>


    <body>
        <div id="wrap">
            {% include 'navbar.html' %}

              {% if messages %}
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="cc-messages" class="container">
                     {% for message in messages %}
                       <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
                         <button type="button" class="close" data-dismiss="alert">×</button>
                         {{ message|safe }}
                       </div>
                     {% endfor %}
                    </div>
                  </div>
                </div>
              {% endif %}

            {% block content %}{% endblock %}
        </div>

        {% include 'footer.html' %}

        <!-- Cart modal -->
        <div class="modal fade" id="hb-cart-modal" tabindex="-1" aria-labelledby="hb-cart-modal-Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="hb-cart-modal-Label">{% trans 'Cart' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div id="hb-cart-content"></div>
              </div>
              <div class="modal-footer">
                  <div class="row col-5 py-3 mx-auto position-relative">
                    <button type="button" class="btn btn-dark rounded-0 mx-auto position-relative mt-4" id="show-order-modal" data-bs-toggle="modal" data-bs-target="#hb-order-modal" style="font-family: IBM Plex Mono;">{% trans 'Make order' %}</button>
                    <button type="button" class="btn btn-secondary rounded-0 mt-4 mb-3 " style="font-family: IBM Plex Mono;" data-bs-dismiss="modal">{% trans 'Back to shop' %}</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Cart modal -->

        <!-- Order modal -->
        <div class="modal fade" id="hb-order-modal" tabindex="-1" aria-labelledby="hb-order-modal-Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content bg-cart-modal-color">
              <div class="modal-header">
                <h5 class="modal-title" id="hb-order-modal-Label">{% trans 'Order' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div id="hb-order-content"></div>
              </div>
            </div>
          </div>
        </div>
        <!-- Order modal -->

        <!-- Choose size modal -->
        <div class="modal fade" id="hb-choose-size" tabindex="-1" aria-labelledby="hb-order-modal-Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content bg-cart-modal-color">
              <div class="modal-header">
                <h5 class="modal-title" id="hb-choose-size-Label">{% trans 'Choose size' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <div class="mt-5 mb-5 d-flex justify-content-center" style="white-space: nowrap; background-opacity: 0;">
                    <div id="modal-sizes"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Choose size modal -->

    </body>

    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{{ STATIC_URL }}js/script.js"></script>
    <script id="widget-wfp-script" language="javascript" type="text/javascript" src="https://secure.wayforpay.com/server/pay-widget.js"></script>
    {% block js %}{% endblock %}

</html>

human_hub/templates/footer.html
{% load i18n %}
<footer class="text-center text-lg-start bg-light text-muted mt-2">
  <!-- Section: Info  -->
  <section class="d-flex justify-content-center p-2 border-top footer-border-color-black">
          <a href="{% url 'info:discounts' %}" title="{% trans 'Discounts' %}">
            <button type="button" style="width: auto;" class="btn-footer btn-outline-dark rounded-0 mb-3 mt-3 btn-sm mx-3">{% trans 'Discounts' %}</button></a>
          <a href="{% url 'info:sizing' %}" title="{% trans 'Sizing' %}">
            <button type="button" style="width: auto;" class="btn-footer btn-outline-dark rounded-0 mb-3 mt-3 btn-sm mx-3">{% trans 'Sizing' %}</button></a>
          <a href="{% url 'info:shipping' %}" title="{% trans 'SHipping' %}">
            <button type="button" style="width: auto;" class="btn-footer btn-outline-dark rounded-0 mb-3 mt-3 btn-sm mx-3">{% trans 'Shipping' %}</button></a>
          <a href="{% url 'info:refund' %}" title="{% trans 'Refund' %}">
            <button type="button" style="width: auto;" class="btn-footer btn-outline-dark rounded-0 mb-3 mt-3 btn-sm mx-3">{% trans 'Refund' %}</button></a>
  </section>
  <!-- Section: Info  -->
  <!-- Section: About project  -->
  <div class="row">
    <div class="col-xs-8 col-sm-7 col-md-8 col-lg-7 text-center mx-auto mt-1">
      <section class="col-10 d-flex justify-content-center mx-auto p-1 border-top footer-border-color-black">
            <a class="nav-link footer_button" href="{% url 'info:contacts' %}" title="{% trans 'Contacts' %}">{% trans 'Contacts' %}</a>
            <a class="nav-link footer_button" href="{% url 'info:about' %}" title="{% trans 'About project' %}">{% trans 'About project' %}</a>
            <a class="nav-link footer_button" href="{% url 'info:terms' %}" title="{% trans 'Terms' %}">{% trans 'Terms' %}</a>
      </section>
    </div>
  </div>
  <!-- Section: About project-->
  <!-- Section: Social  -->
  <section class="d-flex justify-content-center p-2">
      <a class="mx-5" href="https://twitter.com/">
        <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 24 24" width="24px" height="24px">
          <path d="M 24 4.300781 C 23.101563 4.699219 22.199219 5 21.199219 5.101563 C 22.199219 4.5 23 3.5 23.398438 2.398438 C 22.398438 3 21.398438 3.398438 20.300781 3.601563 C 19.300781 2.601563 18 2 16.601563 2 C 13.898438 2 11.699219 4.199219 11.699219 6.898438 C 11.699219 7.300781 11.699219 7.699219 11.800781 8 C 7.699219 7.800781 4.101563 5.898438 1.699219 2.898438 C 1.199219 3.601563 1 4.5 1 5.398438 C 1 7.101563 1.898438 8.601563 3.199219 9.5 C 2.398438 9.398438 1.601563 9.199219 1 8.898438 C 1 8.898438 1 8.898438 1 9 C 1 11.398438 2.699219 13.398438 4.898438 13.800781 C 4.5 13.898438 4.101563 14 3.601563 14 C 3.300781 14 3 14 2.699219 13.898438 C 3.300781 15.898438 5.101563 17.300781 7.300781 17.300781 C 5.601563 18.601563 3.5 19.398438 1.199219 19.398438 C 0.800781 19.398438 0.398438 19.398438 0 19.300781 C 2.199219 20.699219 4.800781 21.5 7.5 21.5 C 16.601563 21.5 21.5 14 21.5 7.5 C 21.5 7.300781 21.5 7.101563 21.5 6.898438 C 22.5 6.199219 23.300781 5.300781 24 4.300781"/></svg></a>
      <a class="mx-5" href="https://www.facebook.com/">
        <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 24 24" width="24px" height="24px">
          <path d="M12,2C6.477,2,2,6.477,2,12c0,5.013,3.693,9.153,8.505,9.876V14.65H8.031v-2.629h2.474v-1.749 c0-2.896,1.411-4.167,3.818-4.167c1.153,0,1.762,0.085,2.051,0.124v2.294h-1.642c-1.022,0-1.379,0.969-1.379,2.061v1.437h2.995 l-0.406,2.629h-2.588v7.247C18.235,21.236,22,17.062,22,12C22,6.477,17.523,2,12,2z"/></svg></a>
      <a class="mx-5" href="https://www.instagram.com/">
        <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 24 24" width="24px" height="24px">
          <path d="M 8 3 C 5.239 3 3 5.239 3 8 L 3 16 C 3 18.761 5.239 21 8 21 L 16 21 C 18.761 21 21 18.761 21 16 L 21 8 C 21 5.239 18.761 3 16 3 L 8 3 z M 18 5 C 18.552 5 19 5.448 19 6 C 19 6.552 18.552 7 18 7 C 17.448 7 17 6.552 17 6 C 17 5.448 17.448 5 18 5 z M 12 7 C 14.761 7 17 9.239 17 12 C 17 14.761 14.761 17 12 17 C 9.239 17 7 14.761 7 12 C 7 9.239 9.239 7 12 7 z M 12 9 A 3 3 0 0 0 9 12 A 3 3 0 0 0 12 15 A 3 3 0 0 0 15 12 A 3 3 0 0 0 12 9 z"/></svg></a>
  </section>
  <!-- Section: Social-->
</footer>

human_hub/templates/navbar.html
{% load i18n %}
{% load showcase_tags %}

  <nav class="navbar navbar-dark bg-dark py-4">
    <div class="container-fluid">

      <button class="navbar-toggler navbar-toggler-icon:focus" style="box-shadow:none; border: 0px !important;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <a class="navbar-brand mx-auto fixed-top position-relative" href="{% url 'showcase:showcase' %}" >
        <img class="hb-gallery ms-5" src="{{ STATIC_URL }}img/Bornto_logo.png"></a>

      <div class="mx-2" style="float:right;">
        <a class="hb-cart-link visible-xs-inline-block hb-mobile-cart" id="show-cart-modal" data-bs-toggle="modal" data-bs-target="#hb-cart-modal">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
             <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
             </svg> | <span id="hb-cart-total">{{ request.cart_amount }}</span>
        </a>
      </div>

    </div>
  </nav>

  <div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-light p-4 hb-main-menu-background-color">

        <form class="d-flex" style="font-family: IBM Plex Mono;">
          <button class="btn ms-2 btn-outline-secondary rounded-0 hb-main-menu-color" type="submit" style="font-family: IBM Plex Mono;">{% trans 'Search' %}</button>
            <input class="form-control mx-2 bg-transparent rounded-0 hb-main-menu-color" style="font-family: IBM Plex Mono;" type="search" placeholder="{% trans 'Type what to search' %}" aria-label="Search">
        </form>

        <div class="dropdown mt-3">
            <div class="select">
                <button class="btn btn-outline-secondary dropdown-toggle btn-sm mb-0 h1 fs-5 hb-main-menu-color" style="box-shadow:none; border: 0px !important; font-family: IBM Plex Mono;" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="true">
                  {% trans 'Currency' %}
                </button>
                <input type="hidden" name="lang">
                <ul class="dropdown-menu val dropdown-menu-dark mb-0 h1 fs-5" aria-labelledby="dropdownMenuButton1">
                  <li class="ms-3 mb-3" style="font-family: IBM Plex Mono;" id="grn">{% trans 'UAH' %}</li>
                  <li class="ms-3 my-3" style="font-family: IBM Plex Mono;" id="usd">{% trans 'USD' %}</li>
                  <li class="ms-3 mt-3" style="font-family: IBM Plex Mono;" id="eur">{% trans 'EUR' %}</li>
                </ul>
            </div>
        </div>

        <div class="dropdown mt-1">
            <div class="select">
                <button class="btn btn-outline-secondary dropdown-toggle btn-sm mb-0 h1 fs-5 hb-main-menu-color" style="box-shadow:none; border: 0px !important; font-family: IBM Plex Mono;" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="true">
                  {% trans 'Language' %}
                </button>
                <input type="hidden" name="lang">
                <ul class="dropdown-menu lang dropdown-menu-dark mb-0 h1 fs-5" aria-labelledby="dropdownMenuButton1">
                  <li class="ms-3 mb-3" style="font-family: IBM Plex Mono;" id="en">{% trans 'English' %}</li>
                  <li class="ms-3 my-3" style="font-family: IBM Plex Mono;" id="uk">{% trans 'Ukrainian' %}</li>
                  <li class="ms-3 mt-3" style="font-family: IBM Plex Mono;" id="ru">{% trans 'Russian' %}</li>
                </ul>
            </div>
        </div>

          <ul class="nav navbar-nav navbar-right ms-2 mt-3 mb-0 h1 fs-5">
            <li class="nav-item visible-xs">
                <a class="nav-link hb-main-menu-color" href="{% url 'info:about' %}" style="font-family: IBM Plex Mono;" title="{% trans 'About project' %}">
                  {% trans 'About project' %}
                </a>
            </li>
          </ul>

            {% get_categories request %}

          <ul class="nav navbar-nav navbar-right ms-2 mt-4 mb-0 h1 fs-5">
            <li class="nav-item visible-xs">
                <a class="nav-link hb-main-menu-color" style="font-family: IBM Plex Mono;" href="{% url 'info:discounts' %}" title="{% trans 'Discounts' %}">
                  {% trans 'Discounts' %}
                </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right ms-2 mb-0 h1 fs-5">
            <li class="nav-item visible-xs">
                <a class="nav-link hb-main-menu-color" style="font-family: IBM Plex Mono;" href="{% url 'info:sizing' %}" title="{% trans 'Sizing' %}">
                  {% trans 'Sizing' %}
                </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right ms-2 mb-0 h1 fs-5">
            <li class="nav-item visible-xs">
                <a class="nav-link hb-main-menu-color" style="font-family: IBM Plex Mono;" href="{% url 'info:shipping' %}" title="{% trans 'Shipping' %}">
                  {% trans 'Shipping' %}
                </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right ms-2 mb-0 h1 fs-5">
            <li class="nav-item visible-xs">
                <a class="nav-link hb-main-menu-color" style="font-family: IBM Plex Mono;" href="{% url 'info:refund' %}#payment" title="{% trans 'Purchase returns' %}">
                  {% trans 'Purchase returns' %}
                </a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right ms-2 mt-4 mb-0 h1 fs-5 ">
            <li class="nav-item visible-xs">
                <a class="nav-link hb-main-menu-color" style="font-family: IBM Plex Mono;" href="{% url 'info:contacts' %}" title="{% trans 'Contacts' %}">
                  {% trans 'Contacts' %}
                </a>
            </li>
          </ul>

  </div>
  </div>