human_hub/human_hub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = []

urlpatterns += (
    i18n_patterns(
    path('', include('showcase.urls')),
    path('administration/', include('administration.urls')),
    path('orders/', include('orders.urls')),
    path('info/', include('info.urls')),
    path('admin/', admin.site.urls),
    )
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

human_hub/info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('discounts/', views.DiscountsView.as_view(), name='discounts'),
    path('refund/', views.RefundView.as_view(), name='refund'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('sizing/', views.SizingView.as_view(), name='sizing'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'about'}, name='about_tag'),
    path('contacts_tag/', views.AboutTagView.as_view(), {'tag': 'contacts'}, name='contacts_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'discounts'}, name='discounts_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'refund'}, name='refund_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'shipping'}, name='shipping_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'sizing'}, name='sizing_tag'),
    path('about_tag/', views.AboutTagView.as_view(), {'tag': 'aboutermst'}, name='aboutermst_tag'),

]

human_hub/showcase/urls.py
from django.urls import path
from . import views

app_name = 'showcase'

urlpatterns = [
    path('', views.ShowcaseView.as_view(), name='showcase'),
    path('category/<int:category_id>/', views.CategoryPageView.as_view(), name='category_page'),
    path('item/<int:item_id>/', views.ItemPageView.as_view(), name='item_page'),
    path('category/<int:item_id>/sizes/', views.ChooseSizes, name='choose_sizes'),
    path("currency/<str:valuta>/", views.cart_val, name="currency"),
]

human_hub/showcase/models.py
from django_resized import ResizedImageField
from solo.models import SingletonModel


from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _



class Categories(models.Model):
    name = models.CharField(_("name"), max_length=70)
    details = models.TextField(_("details"), blank=True)
    title_tag = models.CharField(_("title tag"), max_length=70, blank=True, default="")
    description_tag = models.CharField(_("description tag"), max_length=280, blank=True, default="")
    sequence = models.PositiveSmallIntegerField(_("sequence"), default=0)
    showcase_displayed = models.BooleanField(_("showcase_displayed"), default=True)

    class Meta:
        ordering = ("sequence",)
        verbose_name = _("Categories")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return u"%s" % self.name

    def get_items(self):
        return Items.objects.filter(category=self)

    def get_first2items(self):
        return Items.objects.filter(category=self).order_by("-added")[:2]


    def get_rest_items(self):
        return Items.objects.filter(category=self).order_by("-added")[2:]


class Items(models.Model):
    name = models.CharField(_("name"), max_length=250)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    image = ResizedImageField(size=[2500, 2500], upload_to="photos/%Y/%m/%d")
    image_small = ResizedImageField(size=[300, 300], crop=["middle", "center"], upload_to="small_photos/%Y/%m/%d", editable=False,)
    description = models.TextField(_("how it fits"), blank=True, default="")
    details = models.TextField(_("details"), blank=True, default="")
    price = models.PositiveSmallIntegerField(_("price"), default=0)
    price_description = models.CharField(_("price_description"), max_length=250, default=_("Grn."))
    views = models.PositiveIntegerField(_("views"), default=0)
    views_today = models.PositiveIntegerField(_("views today"), default=0)
    views_month = models.CharField(_("views month"), default=0, max_length=512)
    showcase_displayed = models.BooleanField(_("showcase_displayed"), default=True)
    showcase_new = models.BooleanField(_("showcase_new"), default=True)
    title_tag = models.CharField(_("title tag"), max_length=70, blank=True, default="")
    description_tag = models.CharField(_("description tag"), max_length=280, blank=True, default="")
    added = models.DateTimeField(_("added"), auto_now_add=True)

    class Meta:
        ordering = ("-views",)
        verbose_name = _("items")
        verbose_name_plural = _("items")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.was_views_today = self.views_today

    def __str__(self):
        return u"%s (%s) (%s)" % (self.name, self.category.name, self.description)


    def get_balance(self):
        return Balance.objects.filter(item=self)

    def get_amount(self):
        balances = Balance.objects.filter(item=self)
        for balance in balances:
            if balance.amount > 0:
                return True
        return False

    def sorting(self):
        return (
            Balance.objects.filter(item=self).aggregate(Sum("amount"))
            * self.views_per_month
        )


class Sizes(models.Model):
    name = models.CharField(_("name"), max_length=20)
    categories = models.ForeignKey(Categories, on_delete=models.CASCADE)
    description = models.TextField(_("description"), blank=True, default="")
    sequence = models.PositiveSmallIntegerField(_("sequence"), default=0)

    class Meta:
        ordering = ("sequence",)
        verbose_name = _("Sizes")
        verbose_name_plural = _("Sizes")

    def __str__(self):
        return u"%s" % self.name


class Photo(models.Model):
    item = models.ForeignKey(Items, on_delete=models.CASCADE)
    image = ResizedImageField(size=[2500, 2500], upload_to="photos/%Y/%m/%d")
    image_small = ResizedImageField(
        size=[300, 300],
        crop=["middle", "center"],
        upload_to="small_photos/%Y/%m/%d",
        editable=False,
    )
    added = models.DateTimeField(_("added"), auto_now_add=True)

    class Meta:
        ordering = ("added",)
        verbose_name = _("Photo")
        verbose_name_plural = _("Photos")

    def save(self, *args, **kwargs):
        if not self.image._committed:
            self.image_small = self.image.file
        super().save(*args, **kwargs)

    def __str__(self):
        return u"%s - %s" % (self.item.name, self.added)


class Balance(models.Model):
    item = models.ForeignKey(Items, on_delete=models.CASCADE)
    size = models.ForeignKey(Sizes, on_delete=models.CASCADE)
    amount = models.IntegerField(_("amount"), default=0)

    class Meta:
        ordering = ("id",)
        verbose_name = _("Amount")
        verbose_name_plural = _("Amount")

    def __str__(self):
        return u"%s - %s - %s" % (self.item.name, self.size.name, self.amount)


class BalanceLog(models.Model):
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    old_value = models.IntegerField(_("old value"))
    new_value = models.IntegerField(_("new value"))
    arrival = models.BooleanField(_("arrival"), default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    change_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-change_time",)
        verbose_name = _("Balance log")
        verbose_name_plural = _("Balance logs")

    def __str__(self):
        return "%s - %s" % (self.balance, self.change_time)


class Banner(models.Model):
    image_showcase = ResizedImageField(size=[2000, 300], upload_to="photos/%Y/%m/%d")
    image_category = ResizedImageField(size=[2000, 300], upload_to="photos/%Y/%m/%d")

    class Meta:
        verbose_name = _("Banners")
        verbose_name_plural = _("Banners page")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if Banner.objects.count() != 1:
            self.delete()


class Config(SingletonModel):
    dollar_rate = models.DecimalField(
        _("dollar rate"), max_digits=5, decimal_places=2, default=1
    )
    euro_rate = models.DecimalField(
        _("euro rate"), max_digits=5, decimal_places=2, default=1
    )
    price_description = models.CharField(
        _("price_description"), max_length=250, default=gettext("Grn.")
    )
    price_description_usd = models.CharField(
        _("price_description"), max_length=250, default=gettext("Usd.")
    )
    price_description_eur = models.CharField(
        _("price_description"), max_length=250, default=gettext("Eur.")
    )
    static = models.CharField(
        _("static url"), max_length=250, default="https://catcult.club/static/"
    )
    media = models.CharField(
        _("media url"), max_length=250, default="https://catcult.club/media/"
    )
    merchant_account = models.CharField(
        _("merchant account"), max_length=64, default=""
    )
    merchant_secret = models.CharField(_("merchant secret"), max_length=128, default="")
    merchant_domain_name = models.CharField(
        _("merchant domain name"), max_length=64, default=""
    )
    service_url = models.CharField(_("service URL"), max_length=512, default="")

    class Meta:
        ordering = ("dollar_rate",)
        verbose_name = _("Config")
        verbose_name_plural = _("Config")

    def __str__(self):
        return u"%s" % self.dollar_rate


@receiver(post_save, sender=Items)
def create_item_balance(instance, created, **kwargs):
    if created:
        category = instance.category
        sizes = Sizes.objects.filter(categories=category)
        for size in sizes:
            balance = Balance(item=instance, size=size)
            balance.save()

human_hub/showcase/views.py
from jsonview.decorators import json_view
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import gettext_lazy as _
from showcase.models import Photo, Categories, Items, Sizes, Balance, Banner


class ShowcaseView(View):
    def get(self, request):
        banner = Banner.objects.all()[0]
        cat = Categories.objects.all()
        categories = []

        for category in cat:
            categories.append((category.get_first2items(), category.get_rest_items(), category,))
        if cat:
            title_tag = cat[0].title_tag
            description_tag = cat[0].description_tag
        else:
            title_tag = _("main pae title_tag")
            description_tag = _("main pae description_tag")

        return render(
            request,
            'showcase/showcase.html',
            {
                "categories": categories,
                "title_tag": title_tag,
                "description_tag": description_tag,
                'banner': banner,
            },
        )


class CategoryPageView(View):
    def get(self, request, category_id):
        banner = Banner.objects.all()[0]
        cat = get_object_or_404(Categories, id=category_id)
        items = Items.objects.filter(category=category_id)

        return render(
            request,
            'showcase/category_page.html',
            {
                'category': cat,
                'items': items,
                'banner': banner,
            }
        )


class ItemPageView(View):
    def get(self, request, item_id):
        item = get_object_or_404(Items, id=item_id)
        photos = Photo.objects.all().filter(item=item)
        sizes = Sizes.objects.all().filter(categories=item.category)
        for size in sizes:
            size.amount = Balance.objects.get(item=item, size=size).amount

        return render(
            request,
            'showcase/item_page.html',
            {
                'item': item,
                'photos': photos,
                'sizes': sizes,
            }
        )


@csrf_exempt
@json_view
def ChooseSizes(request, item_id):
    item = get_object_or_404(Items, id=item_id)
    sizes = Sizes.objects.all().filter(categories=item.category)

    for size in sizes:
        size.amount = Balance.objects.get(item=item, size=size).amount

    t = loader.get_template('showcase/choose_sizes.html')
    c = {'sizes': sizes, 'item': item}
    html = t.render(c, request)

    return {'success': True, 'html': html}


@json_view
def cart_val(request, valuta):
    request.session['valuta'] = valuta

    return {'success': True}

human_hub/showcase/templates/showcase/category_page.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
{% load showcase_tags %}

<div class="row">
    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-7 text-center mx-auto">

        <div class="col-xs-9 col-sm-9 col-md-12 col-lg-12 text-center mx-auto">
            <img class='img-fluid w-80' src="{{ MEDIA_URL }}{{ banner.image_category }}" alt=""/>
        </div>


        <div class="container mt-1 footer-border-color-black border-bottom col-10">
            <div class="row">
                <div class="col d-flex justify-content-center">
                    <div class="text-center w-5">
                        <label class="toggle">
                            <span class="onoff"></span>
                                <input type="checkbox"/>
                                    <img class="w-5 p-3 mt-1" id="icontoggler" onclick="changeImage()" style="height:50px;" src="{{ STATIC_URL }}img/category_toggle.png">
                            <span class="slider"></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>

        <div class="container--wide">
            <div class="row mt-4 collection-template__products" id="category-style">

                {% if items %}
                {% for item in items %}
                <div class="product-card has-hover-image mb-3">
                    <a class="product-card__link-overlay" href="{% url 'showcase:item_page' item.id  %}"  aria-label="">
                        <img class='img-fluid' style="height:auto; width:100%;" src="{{ MEDIA_URL }}{{ item.image }}"/>
                    </a>
                    <div class="container--wide" style="padding-right: 0px !important; margin-right: 0px; !important">
                        <div class="row">
                            <div class="col-8">
                                <h3 class="row-full item-name-in-category-page">
                                    <span class="item-name-in-category-page kuku">{{ item.name }}</span>
                                </h3>
                                <div class="row item-price-category-page">
                                    <span style="float:left !important; margin-left: 0rem !important;">{% get_price_itempage request item.id %}</span>
                                </div>
                            </div>
                            <div class="col-4" style="padding-left: 0px !important;">
                                <button type="button" class="btn btn-dark rounded-0 col-4 choose-size" style="width: 100%;" data-id="{{ item.id }}" data-bs-toggle="modal" data-bs-target="#hb-choose-size"><i class="bi bi-cart text-light"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}

            </div>
        </div>

    </div>
</div>
{% endblock %}
{% block js %}
<script src="{{ STATIC_URL }}js/category_page.js"></script>
{% endblock %}

human_hub/showcase/templates/showcase/choose_sizes.html
<div class="item-modal-sizes" id="{{ item.id }}"></div>
{% for size in sizes %}
{% if size.amount <= 0 %}
    <label class="btn btn-dark size_button_font mx-1 rounded-0 disabled" style="font-family: IBM Plex Mono;" for="{{ size.name }}">{{ size.name }}</label>
{% else %}
    <input type="checkbox" name="{{ size.name }}" id="{{ size.name }}" data-id= "{{ size.id }}" class="btn-check mx-1 size-class" autocomplete="off" />
    <label class="btn btn-dark size_button_font mx-1 rounded-0" style="font-family: IBM Plex Mono;" for="{{ size.name }}">{{ size.name }}</label>
{% endif %}
{% endfor %}
{% block js %}
<script src="{{ STATIC_URL }}js/choose_sizes.js"></script>
{% endblock %}

human_hub/showcase/templates/showcase/showcase.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load showcase_tags %}

{% block title %}{{ title_tag }}{% endblock %}
{% block description %}{{ description_tag }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-7 text-center mx-auto">

            <img class='img-fluid w-80' src="{{ MEDIA_URL }}{{ banner.image_showcase }}" alt="" />

    <!--   CATEGORY   -->
        {% for category in categories %}
        <!--   TWO FIRST ITEMS IN CATEGORY   -->
        <div class="container--wide">
            <div class="row mt-4 collection-template--column-view">

                <div class="product-card has-hover-image mb-3">
                    <a class="product-card__link-overlay" href="{% url 'showcase:item_page' category.0.0.id %}">
                        <img class='img-fluid' style="height:auto; width:100%;" src="{{ MEDIA_URL }}{{ category.0.0.image }}"/>
                    </a>
                    <div class="container--wide" style="padding-right: 0px !important; margin-right: 0px; !important">
                        <div class="row">
                            <div class="col-8">
                                <h3 class="row-full item-name-in-category-page">
                                    <span class="item-name-in-category-page">{{ category.0.0.name }}</span>
                                </h3>
                                <div class="row item-price-category-page">
                                    <span style="float:left !important; margin-left: 0rem !important;">{% get_price_itempage request category.0.0.id %}</span>
                                </div>
                            </div>
                            <div class="col-4" style="padding-left: 0px !important;">
                                <button type="button" class=" btn btn-dark rounded-0 col-4 choose-size-showcase" style="width: 100%;" data-id="{{ category.0.0.id }}" data-bs-toggle="modal" data-bs-target="#hb-choose-size"><i class="bi bi-cart text-light"></i></button>
                            </div>
                        </div>
                    </div>
                </div>

                {% if category.0.1 %}
                <div class="product-card has-hover-image mb-3">
                    <a class="product-card__link-overlay" href="{% url 'showcase:item_page' category.0.1.id %}"  aria-label="">
                        <img class='img-fluid' style="height:auto; width:100%;" src="{{ MEDIA_URL }}{{ category.0.1.image }}"/>
                    </a>
                    <div class="container--wide" style="padding-right: 0px !important; margin-right: 0px; !important">
                        <div class="row">
                            <div class="col-8">
                                <h3 class="row-full item-name-in-category-page">
                                    <span class="item-name-in-category-page">{{ category.0.1.name }}</span>
                                </h3>
                                <div class="row item-price-category-page">
                                    <span style="float:left !important; margin-left: 0rem !important;">{% get_price_itempage request category.0.1.id %}</span>
                                </div>
                            </div>
                            <div class="col-4" style="padding-left: 0px !important;">
                                <button type="button" class="btn btn-dark rounded-0 col-4 choose-size-showcase" style="width: 100%;" data-id="{{ category.0.1.id }}" data-bs-toggle="modal" data-bs-target="#hb-choose-size"><i class="bi bi-cart text-light"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <!--   TWO FIRST ITEMS IN CATEGORY   -->

        <!--   CAROUSEL   -->
        <div id="carouselShowcasePage" class="carousel" data-bs-ride="carousel">
            <div class="carousel-inner carousel-inner-showcase">
            {% if category.1 %}
                {% for item in category.1 %}
                <div class="carousel-item carousel-item-showcase active" style="width: 20%;">
                    <div class="card-carousel-showcase">

                        <a class="product-card__link-overlay" href="{% url 'showcase:item_page' item.id %}" aria-label="">
                        <img class='img-fluid' style="height:auto; width:auto;" src="{{ MEDIA_URL }}{{ item.image }}"/></a>
                        <div class="card-body" style="justify-content: center; display: flex; align-items: center; padding-bottom: 0.2rem;">
                            <div style="float: left;">
                                <h5 class="item-name-in-showcase-page" style="white-space: normal;">{{ item.name }}</h5>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselShowcasePage" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>

            <button class="carousel-control-next" type="button" data-bs-target="#carouselShowcasePage" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
            {% endif %}

        </div>
        <!--   CAROUSEL   -->
        <div class="row">
            <a class="btn btn-dark btn-lg rounded-0 mt-5 mb-5 mx-auto" href="{% url 'showcase:category_page' category.2.id %}" role="button" style="font-family: IBM Plex Mono; height:auto; max-width:70%;">{% trans 'Go to' %} {{ category.2.name }}</a>
        </div>
        {% endfor %}
    <!--   CATEGORY   -->

    </div>
</div>
{% endblock %}
{% block js %}
<script src="{{ STATIC_URL }}js/showcase.js"></script>
{% endblock %}